version: "3.7"
services: 
  server:
    build: "./api"
    container_name: node_container
    volumes:
      - ./api:/usr/app
    ports: 
      - "4000:4000"
    restart: always
  mongo:
    image: mongo
    ports: 
      - "27017:27017"
    restart: always